### ISSUE TITLE
launch.sh process stops when the Round-Trip Time (RTT) exceeds 27~37 

### ISSUE THREAD

**Issue by limlynn** [NUS-SNL/Gordon#3]
Firstly, I want to express my gratitude to the author for their work on this open-source project. It has been a valuable resource for my project. However, I've encountered an issue where the process stops when the Round-Trip Time (RTT) exceeds 27~37 milliseconds, depending on the web server I'm interacting with. I put the output of the launch.sh script. 

Website : www.naver.com
```
index.html                                             [          <=>                                                                                                  ] 148.02K  32.6KB/s               --------------------------------- RTT-27 ----------------------
--2023-04-12 14:44:25--  https://www.naver.com/
Resolving www.naver.com (www.naver.com)... 104.117.184.239
Connecting to www.naver.com (www.naver.com)|104.117.184.239|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html’

index.html                                             [          <=>                                                                                                  ] 138.17K  35.4KB/s    in 3.9s

2023-04-12 14:44:31 (35.4 KB/s) - ‘index.html’ saved [141482]
```

Website : www.amazon.com

```
index.html                                             [              <=>                                                                                              ] 182.35K  29.3KB/s               --------------------------------- RTT-34 ----------------------
--2023-04-12 14:34:03--  https://www.amazon.com/
Resolving www.amazon.com (www.amazon.com)... 18.172.138.69, 2600:9000:24bf:4800:7:49a5:5fd2:8621, 2600:9000:24bf:3c00:7:49a5:5fd2:8621, ...
Connecting to www.amazon.com (www.amazon.com)|18.172.138.69|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html’

index.html                                             [            <=>                                                                                                ] 195.17K  31.6KB/s    in 6.2s

2023-04-12 14:34:11 (31.6 KB/s) - ‘index.html’ saved [199853]
```

And it's just stopping there. I check the packet using tcpdump and there is no packet after it stops. I want to know the reason but I am not sure which point I need to start with. Thank you in advance.

**Comment by MischMetal** [comment]
Thank you for your kind words!

I am assuming you mean the measurement stops between the 27th and 37th rounds/RTT and not when the RTT is more than 27-37 ms? The RTT of the connection is not explicitly changed during the connection.

As the logs indicate, the process stops because the webpage download has been completed.
`2023-04-12 14:34:11 (31.6 KB/s) - ‘index.html’ saved [199853]`

If you want the measurement to last longer, you would probably have to look for larger files to download from `naver.com` and `amazon.com`. Fortunately, we have already crawled the Alexa websites to find webpages larger than the threshold size mentioned in the paper. You can find the list [here](https://github.com/NUS-SNL/Gordon/blob/master/Alexa20k/full_links.csv).

**Comment by limlynn** [comment]
I wanted to express my heartfelt thanks for your rapid response to my question about the program. 
I appreciate your quick reply to my question. I will check the list and try various sizes of websites.
